  image: docker:18.09-git
  services:
      - docker:18.09-dind
  variables:
    DOCKER_DRIVER: overlay2
    TEMP_COMMIT_IMAGE: $TEMP_COMMIT_IMAGE_REGISTRY/$CI_PROJECT_NAME:$CI_COMMIT_SHORT_SHA # 测试commit镜像：测试镜像存放仓库/项目名称:提交id
    PRODUCTION_COMMIT_IMAGE: $PRODUCTION_IMAGE_REGISTRY/$CI_PROJECT_NAME:$CI_COMMIT_SHORT_SHA # 正式commit镜像，正式镜像存放仓库/项目名称:提交id

  before_script:
    - export IMAGE_TAG=$(git describe --tags) # 输出当前项目tag
    - echo $IMAGE_TAG
    - mkdir -p /etc/docker/certs.d/$CI_REGISTRY
    - cp cert/domain.crt /etc/docker/certs.d/$CI_REGISTRY/ca.crt
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY # 登录私有仓库

  stages:
  - build_image
  - test
  - release
  - rmi_image

  build_image:
    only:
    - master
    - pre-production
    stage: build_image
    script:
      - docker build -t $TEMP_COMMIT_IMAGE .  # master和pre-production触发build

  unit_test:
    stage: test
    only:
    - master
    script:
      - docker run -t --rm --name unit-test-$IMAGE_TAG  $TEMP_COMMIT_IMAGE python t.py

  integrated_test:
    stage: test
    only:
    - master
    script:
      - docker run -it -d --name integrated-test-$IMAGE_TAG $TEMP_COMMIT_IMAGE
      - docker logs integrated_test-$IMAGE_TEST_TAG
      - docker rm -f integrated-test-$IMAGE_TAG

  release_temp_commit_image:
    stage: release
    only:
      - pre-production
    script: 
      - docker push $TEMP_COMMIT_IMAGE

  release_production_image:
    stage: release
    only:
      - tags
    except:
      - /^issue-.*$/
      - /^fix-.*$/
      - /^feature-.*$/
      - master
      - production

    script:
      - export PRODUCTION_IMAGE=$PRODUCTION_IMAGE_REGISTRY/$CI_PROJECT_NAME:IMAGE_TAG
      - echo PRODUCTION_IMAGE
      - docker pull $TEMP_COMMIT_IMAGE
      - docker tag $TEMP_COMMIT_IMAGE $PRODUCTION_COMMIT_IMAGE 
      - docker tag $TEMP_COMMIT_IMAGE $PRODUCTION_IMAGE 
      - docker push $PRODUCTION_COMMIT_IMAGE
      - docker push $PRODUCTION_IMAGE

  release_production_stable_image:
    stage: release
    only:
      - tags
    tags:
    - production
    except:
      - /^issue-.*$/
      - /^fix-.*$/
      - /^feature-.*$/
      - master
      - pre-production

    script:
      - export PRODUCTION_STABLE_IMAGE=$PRODUCTION_IMAGE_REGISTRY/$CI_PROJECT_NAME:IMAGE_TAG-stable
      - echo $PRODUCTION_STABLE_IMAGE
      - docker pull $PRODUCTION_COMMIT_IMAGE
      - docker tag $PRODUCTION_COMMIT_IMAGE $PRODUCTION_STABLE_IMAGE 
      - docker push $PRODUCTION_STABLE_IMAGE

  rmi_image:
    stage: rmi_image
    script:
      - docker rmi -f $TEMP_COMMIT_IMAGE $PRODUCTION_COMMIT_IMAGE $PRODUCTION_IMAGE $PRODUCTION_STABLE_IMAGE

F3R5h68#D